Vagrant.configure("2") do |config|
  config.vm.define "flarevm"
  config.vm.box = "gusztavvargadr/windows-10"

  config.winrm.max_tries = 300
  config.winrm.retry_delay = 2

  config.vm.provider "virtualbox" do |vb|
	vb.name = "FlareVM"
  end

  config.vm.provision "shell", privileged: true, inline: "Set-ExecutionPolicy Unrestricted"
  config.vm.provision "shell", privileged: true, path: "https://raw.githubusercontent.com/mandiant/flare-vm/main/install.ps1"
end
