- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install dependencies
  become: true
  apt:
    name: "{{ apt_packages }}"
    update_cache: true
  tags:
    - sudo

- name: Update all packages to their latest version
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest
    autoclean: true
    autoremove: true
  tags:
    - sudo


- name: Import GPG keys
  include_tasks: gpg.yaml
  tags:
    - gpg

- name: Include git tasks
  include_tasks: git.yaml
  tags:
    - git

- name: Set shell to ZSH
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
  tags:
    - sudo

- name: Include SSH auth
  include_tasks: auth.yaml
  tags:
    - sudo
    - auth

- name: Add Flathub remote to Flatpak
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  when: "'flatpak' in ansible_facts.packages"
  tags: 
    - flatpak

- name: Install flat packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  with_items: "{{ flat_packages }}"
  when: "'flatpak' in ansible_facts.packages"
  tags:
    - flatpak
