#!/bin/bash

# Install files
MIN_INSTALL="htop mc iotop python3 terminator vim zsh"

function show_help {
  echo 'backup [-f] [-h] [-t] [-d] [clean|list|restore|verify]'
  echo '-h :       Show this help'
  echo '-f :       Specify files to use to restore'
  echo '-t :       Specify time range to use, e.g. 1w 2m [list|restore]'
  echo '-d :       Specify target directory [restore]'
  echo '-m :       Backup Doortje directory'
  echo ''
  echo 'restore :  Restore files from backup'
  echo 'clean   :  Clean backup directory from outdated backup files'
  echo 'list    :  List files currently in backup'
}

if [ "$(id -u)" != "0" ]
then
  echo "[WARN] Not root user!"
  exit 1
fi

while getopts "h" opt; do
  case $opt in
    h)
      rm $OUT
      show_help
      exit 0
      ;;
    \?)
      rm $OUT
      exit 1
      ;;
  esac
done

# Arch system
if [ -x /usr/bin/pacman ]
then
  /usr/bin/pacman -Sy $MIN_INSTALL
fi

# DPKG (Debian, Ubuntu, etc)
if [ -x /usr/bin/apt ] 
then
  /usr/bin/apt update
  /usr/bin/apt install -y $MIN_INSTALL
fi

# RPM (Centos, Red Hat)
if [ -x /usr/bin/yum ]
then
  /usr/bin/yum update
  /usr/bin/yum install -y $MIN_INSTALL
fi
