#!/bin/bash

#
#if [ "$(id -u)" != "0" ]
#then
#  echo "[WARN] Not root user!"
#  exit 1
#fi

while getopts "h" opt; do
  case $opt in
    h)
      show_help
      exit 0
      ;;
    \?)
      show_help
      exit 1
      ;;
  esac
done


# Arch system
if [ -x /usr/bin/pacman ]
then
  P_MANAGER="/usr/bin/pacman -S"
# DPKG (Debian, Ubuntu, etc)
elif [ -x /usr/bin/apt ] 
then
  P_MANAGER="/usr/bin/apt install"
# RPM (Centos, Red Hat)
elif [ -x /usr/bin/yum ] 
then
  P_MANAGER="/usr/bin/yum install"
fi

echo "Installing ansible"
sudo $P_MANAGER ansible

# Get playbook
echo "Downloading playbook"
curl -Lq -o /tmp/dot-files.tar.gz https://github.com/rkokkelk/dot-files/archive/master.tar.gz
tar -xvf /tmp/dot-files.tar.gz  -C /tmp/ && cd /tmp/dot-files-master/.playbook

# Running ansible
echo "Starting Ansible"
ansible-playbook --ask-become new.yaml

echo "Removing temp playbook file"
rm -rf /tmp/dot-files-master

exit 0
